# Generated by Django 4.1.7 on 2023-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_followers_alter_post_timestamp_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
